### ISSUE TITLE
Some UI elements are not being tinted

### ISSUE THREAD

**Issue by aabosh** [Sticktron/DarkMessages#1]
- Group chat titles remain to be black and do not turn white
- Names of contacts in a group chat also remain to be black

**Comment by Sticktron** [comment]
can you link a screenshot please?

**Comment by aabosh** [comment]
![screenshot1](https://cloud.githubusercontent.com/assets/7517009/22394501/16ed9868-e4f1-11e6-97b7-2bc6483071af.png)
![screenshot2](https://cloud.githubusercontent.com/assets/7517009/22394502/16fc3a44-e4f1-11e6-874a-3b9be73b2432.png)

**Comment by Sticktron** [comment]
Perfect, thanks. I'll fix those.

**Comment by HiDaN4** [comment]
#5 address this

**Comment by Sticktron** [comment]
Fixed in 1.0.3
