### ISSUE TITLE
Theme Quick Reply?

### ISSUE THREAD

**Issue by joexanderson** [Sticktron/DarkMessages#10]
Will you be able to implement the dark mode for the Quick Reply feature? It's not themed at all.
![img_0021](https://cloud.githubusercontent.com/assets/6763343/22423998/7c1c44aa-e6c2-11e6-86d5-ae59832471f2.PNG)

**Comment by Sticktron** [comment]
Added in v1.1.3

**Comment by joexanderson** [comment]
Awesome! Thanks 😄
