### ISSUE TITLE
Messages have lines and different shades 

### ISSUE THREAD

**Issue by tkz320** [Sticktron/DarkMessages#19]

**Comment by Deodamnatus** [comment]
I have the same problem.
Imgur link: https://imgur.com/a/FnlqL

**Comment by Sticktron** [comment]
Could this be due to an Anemone theme?

**Comment by Deodamnatus** [comment]
Yes you're right. Some themes with a UI option enabled create this bug. Veexillum is the one I use and I don't know about other themes, but enabling the UI option in Anemone will cause this bug
