### ISSUE TITLE
Night shift control doesn't work

### ISSUE THREAD

**Issue by MellowChai** [Sticktron/DarkMessages#25]
When toggling on nighshift control dark messages always stays on even when nightshift is not activated.

**Comment by Sticktron** [comment]
Can you tell me what device, OS version, and language please?

**Comment by MellowChai** [comment]
iPhone 6, iOS 10.2, English.

**Comment by Sohailwahab** [comment]
iPhone 6s iOS 10.2, English. United Status

**Comment by Sohailwahab** [comment]
Thought it works perfectly with Night Shift

**Comment by MellowChai** [comment]
Started working for me :)
