### ISSUE TITLE
Creating Contact or Adding existing contact

### ISSUE THREAD

**Issue by shawndmac** [Sticktron/DarkMessages#46]
Messages can be seen when youre at creating contact or adding the number to the existing contact

**Comment by fullofdata** [comment]
This same thing happened to me too when I added a phone number to an existing contact today.

**Comment by 2PRO2316** [comment]
I also have that problem and it’s really frustrating because it’s hard to see

**Comment by Sticktron** [comment]
I can replicate the issue on 11.2.6.
Needs fixing for sure.

**Comment by schecteracademicservices** [comment]
Same here. I'm guessing the background is transparent rather than black.

**Comment by Matrixnubee** [comment]
I’ve been noticing this issue on my iPhone X running 11.3.1. Very frustrating when needing to create new contacts via messages app.  I hope this gets fixed in a update ASAP!

**Comment by aafloresj15** [comment]
It’s not working it shows the messages in the background.
