### ISSUE TITLE
Grid in the Bubble Text

### ISSUE THREAD

**Issue by Draxed** [Sticktron/DarkMessages#47]
I see this in my app, very ugly. 

https://imgur.com/gallery/h0K6fVp

**Comment by roobs666** [comment]
Same here. Please fix looks horrible.

**Comment by 2PRO2316** [comment]
Me too, it’s been bugging me for so long

**Comment by adam519** [comment]
If you’re talking about the bubbles for messages, it’s due to anemone, at least for me I use muze 3 but once I disabled the UI it then fixed the bubbles looking weird like that

**Comment by roobs666** [comment]
Thanks man I appreciate it. It was bugging me a lot . Fixed the issue 👍🏻

**Comment by Sticktron** [comment]
Just to confirm... it’s the Anemone UI dylib causing the grid? Did you disable it with iCleaner? Or did you just turn off the UI part of the theme your using in the Anemone app itself?

**Comment by roobs666** [comment]
Yes . I went to anemone , disable UI -> Preview -> Apply . Worked for me

**Comment by Sticktron** [comment]
Thank you. I’ll share that info for others who have the same issue :)

**Comment by 2PRO2316** [comment]
Worked for me also👍🏼 but there’s still a problem where I go to the person I wanna text->top right button-> arrow next to my contact’s name and that whole page is mixed together with the messages from our convo with the actual page I’m suppose to be at and it’s a huge issue

**Comment by adam519** [comment]
At least when I click it on it, it does overlap but just for a second, then it goes back to normal

Also I’m having an issue where it isn’t truly black, where the message convo are it, it’s greyed out. Anyone else? 

https://imgur.com/gallery/H99c421
The white outline is grey but when you look up where it says messages, that’s blacked out, idk why that is

**Comment by Sticktron** [comment]
That’s how the theme is supposed to look :)

It wasn’t designed for iPhone X so there wasn’t a reason to make it all black to save battery.

**Comment by Sticktron** [comment]
Caused by Themes (Anemone UI portion).

**Comment by adam519** [comment]
Oh okay I figured it was a glitch or something because it wasn’t all blacked out. Just curious, how come that part is grey, wouldn’t it be easier just to make it all black?

**Comment by Sticktron** [comment]
Apple designed the theme ;)
I just made it apply to iOS and fixed up a few glitches.
