### ISSUE TITLE
Messages app crashing

### ISSUE THREAD

**Issue by hesus618** [Sticktron/DarkMessages#50]
Haven't installed anything new, the bubble color is back to stock, but the background is still dark, it opens up the mesaages app but then instantly crashes. When I try to reopen the messages app it goes all to stock(background and bubbles)

**Comment by hesus618** [comment]
If I turn the tweak off in settings, nothing happens, the background stays black, the bubbles are stock. The only thing that changes is the crashing of the app

**Comment by KWTD** [comment]
Same just happened to me after updating
Cydia (GUI only)
Cydia Compatibility Package
libCSColorPicker
libCSPreferences

**Comment by hesus618** [comment]
What to do?

**Comment by KWTD** [comment]
try deleting libCSColorPicker and libCSPreferences, it worked for me.

**Comment by hesus618** [comment]
Thank you 👌🏻👌🏻👌🏻 it worked for me, it also provided for a fix with eclipse4

**Comment by Sticktron** [comment]
The author of libCS* stuff has updated them to resolve the conflict.
